name: Upload to Release
description: Upload the Sage executable to a new release.

on:
  inputs:
    stem:
      required: true
      type: string
  secrets:
    token:
      required: true

runs:
  using: "composite"
  steps:
  - name: Convert README to html
    uses: docker://pandoc/core:2.9
    with:
      args: >-
        --standalone
        --output=README.html
        README.md

  - name: Bundle executable and README
    shell: bash
    run: |
      mkdir ${{ inputs.stem }}
      cp target/release/sage README.html ${{ inputs.stem }}
      zip ${{ inputs.stem }}

  - name: Upload build artifacts
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.stem }}
      path: ${{ inputs.stem }}.zip

  - name: Upload binaries to the release
    uses: svenstaro/upload-release-action@v2
    if: false
    with:
      repo_token: ${{ secrets.token }}
      tag: ${{ github.ref }}
      file: ${{ inputs.stem }}.zip
      overwrite: true
      file_glob: true
