name: Build Executable

on: push

jobs:
  build_linux:
    name: Build Sage on Linux
    runs-on: ubuntu-latest
    container: ubuntu:14.04 # GLIBC 2.19
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install curl

    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: See what's there
      run: |
        ls -alh target

  build_windows:
    name: Build Sage on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: See what's there
      run: |
        ls -alh target

  build_macos:
    name: Build Sage on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: See what's there
      run: |
        ls -alh target
